### ISSUE TITLE
Runner fails when default `resources` are provider per worker

### ISSUE THREAD

**Issue by ml-evs** [Matgenix/jobflow-remote#14]
I have a config that specifies some default resources for a given worker, e.g.,

```yml
workers: 
  my_worker: 
    type: remote
    host: example.org
    resources:
       queue_name: long_queue
       account: budget123
       time_limit: 3600
```

This config will lead to an error like `ValueError: The following keys are not present in the template: time_limit, processes, queue_name`, as currently the `QResources` field names in the config are not being mapped to the queuing system-specific field names, as the `resources` field in the worker config is just a dict rather than a QResources. I will try to make this change and see what happens.
