### ISSUE TITLE
how to limit number of jobs

### ISSUE THREAD

**Issue by yw-fang** [Matgenix/jobflow-remote#195]
Based on the manul of jobflow remote, it can limit the number of jobs. Could any one show how to enable it? Can we set the limit of jobs for each worker through the ~/.jfremote/project.yaml file? Thank you very much!

**Comment by gpetretto** [comment]
Hi @yw-fang, I suppose you are referring to this functionality: https://matgenix.github.io/jobflow-remote/user/advancedoptions.html#limiting-the-number-of-submitted-jobs. As mentioned there, in the subsection of your worker you can specify the `max_jobs` options. Jobflow-remote will not submit more than that number of jobs to the queue for that project and that worker. 
For example: 
```yaml
workers:
  your_worker_name:
    scheduler_type: slurm
    work_dir: /some/path
    type: remote
    host: some.remote.host
    max_jobs: 5
```

Note that this will not consider other jobs that you may manually submit to the cluster.
