### ISSUE TITLE
Documentation: Additional clarity about pre-specified resource info should be added to the getting started docs

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Matgenix/jobflow-remote#204]
Now that I have the appropriate hardware set up over here, I am finally trying out jobflow-remote! 

I have a very basic question regarding setup. I am using the all-in-one approach where I am running everything from a dedicated login node that can directly jobs to the Slurm queue. However, it is not obvious to me from the setup instructions how to do things like set the default Slurm account name. How do I go about modifying these kinds of default parameters? Apologies if I'm missing this in the docs. If it's not there in a prominent place, this issue can be considered a docs update request :)

```
workers:
  basic:
    type: local
    scheduler_type: slurm
    work_dir: /scratch/gpfs/ROSENGROUP/asrosen/jobflow
    pre_run: conda activate quacc
    timeout_execute: 60
```

**Comment by gpetretto** [comment]
Hi @Andrew-S-Rosen,
good to hear that you are all set now and you are willing to try jobflow-remote.

I think you are right that this is probably not properly covered in the documentation, as information are scattered in different places. I will try to improve it on this point.
Now, to answer your question, everything that is used to generate the submission script should be [set in the `resources`](https://matgenix.github.io/jobflow-remote/user/tuning.html#resources). For each Job, the system will look for the resources details in two places:
1) first it will check if the resources are set in the specific Job. This can be done at submission time by passing the resources to [`submit_flow`](https://matgenix.github.io/jobflow-remote/user/tuning.html#submission) or customizing the values per job with [`set_run_config`](https://matgenix.github.io/jobflow-remote/user/tuning.html#jobconfig)
2) if a value is not defined for a specific Job, it will use the resources specified in the [worker configuration](https://matgenix.github.io/jobflow-remote/user/projectconf.html#workers). In your case an example could be:
 ```yaml
workers:
  basic:
    type: local
    scheduler_type: slurm
    work_dir: /scratch/gpfs/ROSENGROUP/asrosen/jobflow
    pre_run: conda activate quacc
    timeout_execute: 60
    resources: 
        account: xxx
        partition: yyy
        ntasks: 128
        nodes: 1
 ```

Note that the system will only use one of the two. It will not attempt to make a mix. If this is a request, we can consider adding an option to allow that.

Does this answer the question?
