### ISSUE TITLE
remote_job_data.json file missing

### ISSUE THREAD

**Issue by FabiPi3** [Matgenix/jobflow-remote#26]
I am testing jobflow_remote in a very simple case, I use a add job defined in some module:

```
@job
def add(a: int, b: int):
    print("The sum is", a + b)
    return a + b
```

and in the main file I am importing this job and using it in a flow:

```
add_job = add(1, 2)
second_job = add(2, add_job.output)
flow = Flow([keks_job, second_job])
submit_flow(flow, "my_worker")
```

Using a local worker (simple shell execution), everything works as expected. Now I tried to use a remote worker, which I defined in the config file. Checking the config file with `jf project check` leads to only green ticks. Now I submit the flow, and inspect the job status with `jf job list` and the job state goes from `READY` to `ONGOING [CHECKED_OUT]` to `ONGOING [UPLOADED]` to `ONGOING [RUNNING]` to `REMOTE_ERROR [FAILED]`. Looking at the error message with `jf job info -err 1` leads to  the error message:

```
error_remote = file /mnt/beegfs2018/scratch/peschelf/jobflow-remote/f7/bd/e6/f7bde64b-695c-49d6-b8bd-350e7bd9765d/remote_job_data.json for job f7bde64b-695c-49d6-b8bd-350e7bd9765d does not exist 
```

And indeed, checking the specified run_dir in the error message, no such file is present:

```
$ ls
>>> FW.json  FW_offline.json  submit.sh
```

As I said, locally it works fine. Probably it is not a bug, but I don't know what the issue is. Please help me.

For your reference is here the definition of the worker:

```
my_remote_worker:
    scheduler_type: slurm
    work_dir: /mnt/beegfs2018/scratch/peschelf/jobflow-remote
    resources:
    pre_run: conda activate exwoflow
    post_run:
    timeout_execute: 60
    type: remote
    host: dune3.physik.hu-berlin.de
    user: peschelf
    port:
    password:
    key_filename:
    passphrase:
    gateway:
    forward_agent:
    connect_timeout:
    connect_kwargs:
    inline_ssh_env:
    keepalive: 60
    shell_cmd: bash
    login_shell: true
```
