### ISSUE TITLE
Better error handling for incorrectly formatted project YAML

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Matgenix/jobflow-remote#286]
When the project YAML is incorrectly formatted, we get back

```
The active project could not be determined and it is required to execute this command
```

However, this is confusing for new users because it doesn't actually inform the user that their project YAML is misformatted, and it's not clear what went wrong. A clearer error message should be provided, perhaps even just specifying that the YAML is not formatted appropriately.

CC @blaked8619

## Reproduction

To reproduce the issue, make the following project YAML:

```yaml
name: cms
workers:
  example_worker:
    type: local
```

Then run any `jf` command, such as `jf project check --errors`.

**Comment by ThomasWarford** [comment]
Hi,

Related to this, is it possible to write 
```yaml
...
queue:
  store:
    type: MongoURIStore
    uri: mongodb+srv://<user>:<password>@atomate.vz5aurm.mongodb.net/jobflow-remote-example?retryWrites=true&w=majority&appName=atomate
    collection_name: jobs
...
```
Like with atomate2? (https://materialsproject.github.io/atomate2/user/install.html)

I can't tell if I've a formatting mistake or if this is not supported. If not supported, it would be nice if it was.
