### ISSUE TITLE
Two projects, job submission

### ISSUE THREAD

**Issue by JaGeo** [Matgenix/jobflow-remote#89]
I have two projects. When I submit a job with the wrong project (the demon of this project is not running), the job gets submitted to the queue. 

Even when I take the correct project name for the submission, the workflow shows up in both projects when typing:

`jf -p project2 job list`
`jf -p project1 job list`

I am not sure this is intended. (I am using the same database but have specified different collections for outputs)

Related or maybe not related: then the data retrieval from the remote runner fails.

**Comment by gpetretto** [comment]
In principle this is expected. In our idea two different projects may be more or less like two different setups of fireworks with two different launchpads. So, inside each document in the queue Store there is no information about which project it belongs to, as it is basically assuming that all the jobs will belong to just one project.
I am not surprised you get weird behaviour, since you will have two runners working on the same DB collection. There are several things that could go wrong in that case.

There are two options: 
1) use two different databases for the two different projects
2) if you want to keep a single DB also for the queue store you can specify the collection names 
   ```yaml
    queue:
      store:
        '@module': maggma.stores.mongolike
        '@class': MongoStore
        database: DB_NAME
        collection_name: jobs_project1
        ...
      flows_collection: flows_project1
      auxiliary_collection: jf_auxiliary_project1
   ```
   and the same for project2

Would this be fine with you?

On the other hand, since the outputs are mainly based on jobflow's uuid, in principle you could use the same collection for the outputs.

In any case, thanks for raising the issue. I will clarify this in the documentation.
